# Generated by Django 4.2.3 on 2023-07-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='book_id',
        ),
        migrations.AddField(
            model_name='books',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0.005690252350321623, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
